{% set name = "pygaps" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygaps-{{ version }}.tar.gz
  sha256: 76747b468bfcde8a3ef54ee11441447af2d95923e7d18e969af1b9e5d894b740

build:
  noarch: python
  entry_points:
    - pygaps = pygaps.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.16.5
    - pandas
    - scipy >=1.6
    - matplotlib-base
    - coolprop >=6.0
    - gemmi
    - importlib-resources
    - requests
    - xlrd >=1.1
    - xlwt >=1.3
    - openpyxl

test:
  imports:
    - pygaps
  commands:
    - pip check
    - pygaps --help
  requires:
    - pip

about:
  home: https://github.com/pauliacomi/pygaps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for processing adsorption data for porous materials
  doc_url: https://pygaps.readthedocs.io
  dev_url: https://github.com/pauliacomi/pygaps

extra:
  recipe-maintainers:
    - pauliacomi
