{% set name = "pygaps" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygaps-{{ version }}.tar.gz
  sha256: 90a288d5cf117e97961b38569267e78744cc25c8bbaeff105811079070dd7343

build:
  noarch: python
  entry_points:
    - pygaps = pygaps.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - importlib-resources
    - numpy >=1.16.5
    - pandas >=1.1
    - scipy >=1.6
    - matplotlib-base >=3.0
    - coolprop >=6.0
    - adsorption-file-parser >=0.1.7
    - xlrd >=1.1
    - xlwt >=1.3
    - openpyxl
    - gemmi
    - requests

test:
  imports:
    - pygaps
  commands:
    - pip check
    - pygaps --help
  requires:
    - pip

about:
  home: https://github.com/pauliacomi/pygaps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for processing adsorption data for porous materials
  doc_url: https://pygaps.readthedocs.io
  dev_url: https://github.com/pauliacomi/pygaps

extra:
  recipe-maintainers:
    - pauliacomi
